/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  createFileRoute as createFileRoute_,
  createRootRoute as createRootRoute_,
} from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AboutRoute } from "./routes/about";
import { Route as AppointmentRoute } from "./routes/appointment";
import { Route as ContactRoute } from "./routes/contact";
import { Route as GalleryRoute } from "./routes/gallery";
import { Route as IndexRoute } from "./routes/index";
import { Route as ServicesRoute } from "./routes/services";
import { Route as TestimonialsRoute } from "./routes/testimonials";

// Create/Update Routes

const IndexRouteWithContext = IndexRoute.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const AboutRouteWithContext = AboutRoute.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as never);

const ServicesRouteWithContext = ServicesRoute.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRoute,
} as never);

const AppointmentRouteWithContext = AppointmentRoute.update({
  id: "/appointment",
  path: "/appointment",
  getParentRoute: () => rootRoute,
} as never);

const GalleryRouteWithContext = GalleryRoute.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRoute,
} as never);

const TestimonialsRouteWithContext = TestimonialsRoute.update({
  id: "/testimonials",
  path: "/testimonials",
  getParentRoute: () => rootRoute,
} as never);

const ContactRouteWithContext = ContactRoute.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRoute;
      parentRoute: typeof rootRoute;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRoute;
      parentRoute: typeof rootRoute;
    };
    "/appointment": {
      id: "/appointment";
      path: "/appointment";
      fullPath: "/appointment";
      preLoaderRoute: typeof AppointmentRoute;
      parentRoute: typeof rootRoute;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryRoute;
      parentRoute: typeof rootRoute;
    };
    "/testimonials": {
      id: "/testimonials";
      path: "/testimonials";
      fullPath: "/testimonials";
      preLoaderRoute: typeof TestimonialsRoute;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRouteWithContext;
  "/about": typeof AboutRouteWithContext;
  "/services": typeof ServicesRouteWithContext;
  "/appointment": typeof AppointmentRouteWithContext;
  "/gallery": typeof GalleryRouteWithContext;
  "/testimonials": typeof TestimonialsRouteWithContext;
  "/contact": typeof ContactRouteWithContext;
}

export interface FileRoutesByTo {
  "/": typeof IndexRouteWithContext;
  "/about": typeof AboutRouteWithContext;
  "/services": typeof ServicesRouteWithContext;
  "/appointment": typeof AppointmentRouteWithContext;
  "/gallery": typeof GalleryRouteWithContext;
  "/testimonials": typeof TestimonialsRouteWithContext;
  "/contact": typeof ContactRouteWithContext;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRouteWithContext;
  "/about": typeof AboutRouteWithContext;
  "/services": typeof ServicesRouteWithContext;
  "/appointment": typeof AppointmentRouteWithContext;
  "/gallery": typeof GalleryRouteWithContext;
  "/testimonials": typeof TestimonialsRouteWithContext;
  "/contact": typeof ContactRouteWithContext;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/services"
    | "/appointment"
    | "/gallery"
    | "/testimonials"
    | "/contact";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/services"
    | "/appointment"
    | "/gallery"
    | "/testimonials"
    | "/contact";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/services"
    | "/appointment"
    | "/gallery"
    | "/testimonials"
    | "/contact";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithContext;
  AboutRoute: typeof AboutRouteWithContext;
  ServicesRoute: typeof ServicesRouteWithContext;
  AppointmentRoute: typeof AppointmentRouteWithContext;
  GalleryRoute: typeof GalleryRouteWithContext;
  TestimonialsRoute: typeof TestimonialsRouteWithContext;
  ContactRoute: typeof ContactRouteWithContext;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithContext,
  AboutRoute: AboutRouteWithContext,
  ServicesRoute: ServicesRouteWithContext,
  AppointmentRoute: AppointmentRouteWithContext,
  GalleryRoute: GalleryRouteWithContext,
  TestimonialsRoute: TestimonialsRouteWithContext,
  ContactRoute: ContactRouteWithContext,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */
